Oracle SQL Sessions Assignment #1 answers :

1. 
SELECT COUNT(*) AS total_employees FROM EMP;

2. 
SELECT COUNT(*) AS total_departments FROM DEPT;

3. 
SELECT * FROM EMP;

4. 
SELECT * FROM DEPT;

5. 
SELECT SUM(SAL) AS total_salary_paid FROM EMP;

6. 
SELECT SUM(COMM) AS total_commission_paid FROM EMP;

7. 
SELECT DISTINCT JOB FROM EMP WHERE COMM IS NOT NULL;

8. 
SELECT CURRENT_DATE AS system_date;

9. 
SELECT AVG(SAL) AS average_salary FROM EMP;

10. 
SELECT DEPTNO, COUNT(*) AS employees_in_department FROM EMP GROUP BY DEPTNO;

11. 
SELECT DEPTNO, SUM(SAL) AS total_salary_in_department FROM EMP GROUP BY DEPTNO;

12. 
SELECT JOB, COUNT(*) AS employees_per_job FROM EMP GROUP BY JOB;

13. 
SELECT JOB, AVG(SAL) AS average_salary_per_job FROM EMP GROUP BY JOB;

14. 
SELECT EMPNO, TO_CHAR(HIREDATE, 'DD') AS hire_day, TO_CHAR(HIREDATE, 'MM') AS hire_month, TO_CHAR(HIREDATE, 'YYYY') AS hire_year FROM EMP;

15. 
SELECT * FROM EMP ORDER BY DEPTNO;

16. 
SELECT * FROM EMP ORDER BY JOB;

17. 
SELECT * FROM EMP ORDER BY SAL DESC;

18. 
SELECT * FROM EMP ORDER BY DEPTNO ASC, SAL DESC;

19. 
SELECT * FROM EMP WHERE LENGTH(ENAME) = 6;

20. 
SELECT MAX(SAL) AS max_salary, MIN(SAL) AS min_salary FROM EMP;

21. 
SELECT DEPTNO, MAX(SAL) AS max_salary, MIN(SAL) AS min_salary, AVG(SAL) AS avg_salary, SUM(SAL) AS total_salary FROM EMP GROUP BY DEPTNO;

22. 
SELECT * FROM EMP ORDER BY HIREDATE;

23. 
SELECT * FROM EMP ORDER BY HIREDATE DESC LIMIT 1;

24. 
SELECT * FROM EMP ORDER BY HIREDATE ASC LIMIT 1;

25. 
SELECT * FROM EMP ORDER BY TO_CHAR(HIREDATE, 'YYYY') DESC, DEPTNO ASC;

26. 
SELECT * FROM EMP WHERE SAL >= (SELECT AVG(SAL) FROM EMP);

27. 
SELECT * FROM EMP WHERE SAL <= (SELECT AVG(SAL) FROM EMP);

28. 
SELECT * FROM EMP WHERE SAL BETWEEN 2000 AND 4000;

29. 
SELECT * FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP) OR SAL = (SELECT MIN(SAL) FROM EMP);

30. 
SELECT COUNT(*) AS gifts_to_buy FROM EMP WHERE TO_CHAR(HIREDATE, 'MM') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 1), 'MM');
